### ISSUE TITLE
Installation of libyaml-cpp-dev on linux

### ISSUE THREAD

**Issue by Piankero** [ElektraInitiative/libelektra#2256]
I try to use your plugin for parsing yaml files. Unfortunately it requires a dependency (libyaml-cpp-dev >= 0.6)
which is not available in any package repositories at all. Even though in your tutorial you state one can simply install it, all versions are 5.X there.

Could you please provide a method to use your plugin?
I cloned https://github.com/jbeder/yaml-cpp, build it and executed `make install`. Still no luck though.
What do I need to do to have the dependency satisfied?

**Comment by Piankero** [comment]
@sanssecours I think you wrote the plugin, could you help me please?

**Comment by sanssecours** [comment]
> I try to use your plugin for parsing yaml files. Unfortunately it requires a dependency (libyaml-cpp-dev >= 0.6)
> which is not available in any package repositories at all.

While it is true that a package for `yaml-cpp 0.6` is not available for all Linux distributions, a lot of them actually satisfy the dependency of the YAML CPP plugin:

[![Packaging status](https://repology.org/badge/vertical-allrepos/yaml-cpp.svg)](https://repology.org/metapackage/yaml-cpp/versions)

.

> Could you please provide a method to use your plugin?

I can check if I am able to install `yaml-cpp` in a Travis or Jenkins build job. Can you please tell me which OS you are using?

> I cloned https://github.com/jbeder/yaml-cpp, build it and executed make install.

What error message did `make install` print? If `make install` finished successfully, can you please install `pkg-config` and tell me the output of the following command

```
bash -c 'ls $(pkg-config yaml-cpp --variable=libdir)'
```

?

**Comment by Piankero** [comment]
> Can you please tell me which OS you are using?

Linux Mint Sonya. Basically it is Ubuntu xenial.

> can you please install pkg-config and tell me the output of the following command

```
cmake			   libelektragetenv.so.0	      libelektra-io.so.4		  libelektra-pluginprocess.so.4  libelektra.so.4	       libyaml-cpp.so.0.6
elektra			   libelektraintercept-env.so	      libelektra-kdb.so			  libelektra-plugin.so		 libelektratools.so	       libyaml-cpp.so.0.6.2
libelektra-core.so	   libelektraintercept-env.so.0       libelektra-kdb.so.0.8.24		  libelektra-plugin.so.0.8.24	 libelektratools.so.0.8.24     pkgconfig
libelektra-core.so.0.8.24  libelektraintercept-env.so.0.8.24  libelektra-kdb.so.4		  libelektra-plugin.so.4	 libelektratools.so.2	       python2.7
libelektra-core.so.4	   libelektra-invoke.so		      libelektra-meta.so		  libelektra-proposal.so	 libelektra-utility.so	       python3.5
libelektra-ease.so	   libelektra-invoke.so.0.8.24	      libelektra-meta.so.0.8.24		  libelektra-proposal.so.0.8.24  libelektra-utility.so.0.8.24
libelektra-ease.so.0.8.24  libelektra-invoke.so.4	      libelektra-meta.so.4		  libelektra-proposal.so.4	 libelektra-utility.so.4
libelektra-ease.so.4	   libelektra-io.so		      libelektra-pluginprocess.so	  libelektra.so			 libyaml-cpp.a
libelektragetenv.so	   libelektra-io.so.0.8.24	      libelektra-pluginprocess.so.0.8.24  libelektra.so.0.8.24		 libyaml-cpp.so
```

**Comment by Piankero** [comment]
Well, after I deleted the build directory and let cmake do its magix again it is not included.

**Comment by sanssecours** [comment]
Maybe there is still an old version of `yaml-cpp`around on your machine? Can you please check if `pkg-config --modversion yaml-cpp` prints the correct version (`0.6.2`)? Anyway, I changed the content of `.travis.yml` in a test branch to

```yaml
language: cpp

matrix:
  include:
    - os: linux
      name: 🐧 GCC
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC_COMPILER=gcc-8
        - CXX_COMPILER=g++-8
        - COMMON_FLAGS=-Wno-error

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      [[ -n "$CC_COMPILER" ]] && export CC="$CC_COMPILER"
      [[ -n "$CXX_COMPILER" ]] && export CXX="$CXX_COMPILER"
      sudo apt-get -qq update
      sudo apt-get install ninja-build
    fi
  - >
    git clone https://github.com/jbeder/yaml-cpp.git &&
    cd yaml-cpp &&
    mkdir build &&
    cd build &&
    cmake -GNinja -DYAML_CPP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON .. &&
    ninja &&
    sudo ninja install &&
    cd ../..

before_script:
  - mkdir build && cd build
  - cmake -GNinja ..

script:
  - ninja
```

. As you can see [here](https://travis-ci.org/sanssecours/elektra/builds/433706126#L865) the build system recognizes `yaml-cpp` and includes the YAML CPP plugin.
