### ISSUE TITLE
Toml/tablearray problem

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3474]
I played a bit around with the new Toml plugin and I am looking forward to get it merged soon. I noticed a problem but I think it can also be fixed later:

## Steps to Reproduce the Problem

```toml
key = 1

[[tablearray]]
a = 1
b = 2
```

and then changing the key:

```sh
kdb set 'user/tests/storage/key' '2'
```

## Expected Result

```toml
key = 2

[[tablearray]]
a = 1
b = 2
```

## Actual Result

```toml

a = 1
b = 2
key = 2
[[tablearray]]
```

## System Information

- Elektra Version:  #3292
