### ISSUE TITLE
ansible: setting metadata fails the second time

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/libelektra#3816]
## Steps to Reproduce the Problem

```sh
pip3 install ansible
ansible-galaxy collection install elektra_initiative.libelektra
ansible-playbook my-playbook.yml
ansible-playbook my-playbook.yml
```

with (removed) example from https://galaxy.ansible.com/elektra_initiative/libelektra stored as my-playbook.yml

```
- name: elektra module example
  hosts: localhost
  connection: local
  collections:
    - elektra_initiative.libelektra
  tasks:
    - name: set example fruits
      elektra:
        mountpoint: user:/test/example/fruit
        keys:
          apple:
            value: pie
          cherries:
            value: cola
            meta:
              # This adds the type metakey with value string to the key user:/test/example/fruit/cherry
              type: string
```

## Expected Result

Keys with metadata in /test/example, no action when running the second time

## Actual Result

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
 _______________________________
< PLAY [elektra module example] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ___________________________
< TASK [set example fruits] >
 ---------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: in method 'Key___ne__', argument 2 of type 'kdb::Key const &'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619589296.0092552-25859-60391349462027/AnsiballZ_elektra.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619589296.0092552-25859-60391349462027/AnsiballZ_elektra.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/markus/.ansible/tmp/ansible-tmp-1619589296.0092552-25859-60391349462027/AnsiballZ_elektra.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.elektra_initiative.libelektra.plugins.modules.elektra', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_elektra_payload_sp0ao9uy/ansible_elektra_payload.zip/ansible_collections/elektra_initiative/libelektra/plugins/modules/elektra.py\", line 289, in <module>\n  File \"/tmp/ansible_elektra_payload_sp0ao9uy/ansible_elektra_payload.zip/ansible_collections/elektra_initiative/libelektra/plugins/modules/elektra.py\", line 274, in main\n  File \"/tmp/ansible_elektra_payload_sp0ao9uy/ansible_elektra_payload.zip/ansible_collections/elektra_initiative/libelektra/plugins/modules/elektra.py\", line 164, in elektraSet\nTypeError: in method 'Key___ne__', argument 2 of type 'kdb::Key const &'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

## System Information

- Elektra Version: master
- Ansible 2.10.8

## Tasks

- [ ] make example work again
- [ ] readd example to README.md
