### ISSUE TITLE
[FLOSS] VISION.md: example for ansible no longer working

### ISSUE THREAD

**Issue by lukashartl** [ElektraInitiative/libelektra#4333]
## Steps to Reproduce the Problem

```yaml
- name: setup samba workgroup
  connection: local
  hosts: localhost
  tasks:
    - name: set workgroup
      elektra:
        key: "system:/sw/samba/#0/current/global/workgroup"
        value: "MYGROUP"
```

## Actual Result

```
TASK [just a test for example01] **************************************************************
fatal: [example01.example.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (elektra) module: key. Supported parameters include: recommends, keeporder, keys, filename, resolver, plugins, mountpoint."}
```

## Description

The `ansible-libelektra` module has changed, but the documentation in this repo is still old.

**Comment by flo91** [comment]
@markus2330 Maybe also a small issue for the FLOSS course.

**Comment by markus2330** [comment]
Absolutely! @flo91 btw. I added the label lang/config if config files need to be fixed. It's not 100% correct here but Ansible is written in YAML files so it is also not completely wrong.

Btw. the task would be to find a new example that works. There are probably several problems here, in the ansible code and also that we do not have an INI parser compatible to samba. Fixing TOML is a different issue: #3490.

In any case first we need a triage to find out what everything is wrong.

**Comment by Bujuhu** [comment]
Hi!

Here are changes I've made to fix the outdated ansible playbook, which should be functionally identical to the one posted above
`cat playbook.yml`
```yml
- name: setup samba workgroup
  connection: local
  hosts: localhost
  collections:
    - elektra_initiative.libelektra
  tasks:
    - name: set workgroup
      elektra:
        mountpoint: system:/sw/samba/#0/current/global
        keys:
          workgroup:
            value: MYGROUP

```
```
sudo kdb get system:/sw/samba/#0/current/global/workgroup
MYGROUP
```
```
cat /etc/samba/smb.conf
;Ni1
; Generated by the ni plugin using Elektra (see libelektra.org).

workgroup = MYGROUP
```

The only place I could find a full explanation of the options in the most update to date version was [here](https://github.com/ElektraInitiative/ansible-libelektra/blob/main/plugins/modules/elektra.py). Everything else seems to be outdated.
