### ISSUE TITLE
Use Clang-Format to prettify code

### ISSUE THREAD

**Issue by sanssecours** [ElektraInitiative/libelektra#459]
Basically finished, small issues:

- [ ] after `typedef enum` and `extern "C"` there is no newline. But from the docu `BreakBeforeBraces: Allman` already should be the right thing?

# Proposal

[Clang-Format][] is a tool that formats code according to a given set of rules. In my opinion it would make sense to require everyone to use this tool to format their code, before they add something to the repository. This way most of the source files follow a strictly defined style and no one has to care about how many spaces or tabs they need to add to certain parts of their code. For this to work we need to define a code style beforehand. According to [CODING.md](https://github.com/ElektraInitiative/libelektra/blob/master/doc/CODING.md) `.clang-format` should at least contain the following attributes:

```yaml
BreakBeforeBraces: Allman
IndentWidth: 8
ColumnLimit: 72
UseTab: Always
```

I am pretty sure that we need to specify some additional options, and maybe also change the value of `IndentWidth`, for a style that everyone agrees on. The documentation about the various options of `clang-format` is available [here](http://clang.llvm.org/docs/ClangFormatStyleOptions.html).

[Clang-Format]: http://clang.llvm.org/docs/ClangFormat.html

**Comment by markus2330** [comment]
I actually tried to use clang-format, but the predefined styles are quite different to the current code base and creating a new style is a lot of effort.

**Comment by petermax2** [comment]
I think a new style may be worth the effort, if the code formatting happens in an automated way. I still have to read my Elektra code twice before pushing it to find all spaces between function names and parentheses.

**Comment by fberlakovich** [comment]
I agree. A tool that automatically formats code in a final way (e.g. after each commit) would be desirable. I use Eclipse which provides automatic code formatting. However, the configuration options are limited and some formatting still has to be done by hand.

**Comment by markus2330** [comment]
Step 1: @KurtMi please write propose guideline
Step 2: Implement in clang-format

**Comment by sanssecours** [comment]
I recently checked out the various options `clang-format` provides. Here is the current configuration:

```yaml
AccessModifierOffset: -8
AlignAfterOpenBracket: true
AlignConsecutiveAssignments: false
AlignEscapedNewlinesLeft: false
AlignOperands: false
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: true
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: true
BinPackParameters: true
BinPackArguments: true
BreakBeforeBraces: Allman
BreakBeforeTernaryOperators: false
BreakConstructorInitializersBeforeComma: false
ColumnLimit: 72
CommentPragmas: ""
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 8
Cpp11BracedListStyle: false
DerivePointerAlignment: false
DisableFormat: false
IndentCaseLabels: false
IndentWidth: 8
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: true
NamespaceIndentation: None
PointerAlignment: Right
TabWidth: 8
MaxEmptyLinesToKeep: 2
SpaceAfterCStyleCast: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
UseTab: Always
```

I tried to stay as close as possible to the format of `kdb.c`. Here are some topics that came up while I tested the various options:

1. What value should we use for the **width of one tab**? The current setting uses 8 spaces, since this is value that many text editors use by default. Personally I prefer 4 (like Python) or 2 spaces (like Ruby). What do you think?

2. Basically `clang-format` provides two style options, when it comes to **assignments**:

  1. variable = value
  2. variable= value

  Currently the configuration uses option i, which seems to be one most often used in `kdb.c`, although there are some places where there is no space before and after the assignment operator. As far as I can tell, that style is currently not supported by `clang-format`.

3. Should there be a **space before parenthesis** or not? `kdb.c` indicates that we use one space before parenthesis of control structures (`if`, `while`, `for`, …), but no space before otherwise. The current configuration reflects this behaviour. On the other hand, in `kdb.hpp` there is almost always a space before the opening parenthesis. What is the correct behaviour?

4. Since we talked about this in the last meeting: Clang-Format allows you to **keep the format** of certain parts of the document via

 ```c
 // clang-format off
     void    unformatted_code  ;
 // clang-format on
 ```
 
   We can also specify certain parts of comments that should not be reformatted via the regex specified in `CommentPragmas`.

**Comment by markus2330** [comment]
1.) Yes, its 8 because of the default settings of most editors. I think the setting is ok, we can simply increase the maximum line length (ColumnLimit) to e.g. 150 to not have problems with some longer lines in high indentation depth.
2.) assignment should be i., the other places are sloppy. Additionally, we agreed to have spaces around `*`, which is not always the case in kdb.c
3.) There should be spaces before `(`. We are still discussing if `()` (empty parenthesis) need a space before it, too. Would the clang-style support such an exception?
4.) Thanks for the info. I think we should always argue why the formatter is disabled at some places. Is it ok to continue text after `clang-format off`?

Btw. my clang-format-3.5 has following errors with your yaml file (line numbers are wrong because I modified the file to get further errors):
```
YAML:10:35: error: unknown enumerated scalar
AllowShortFunctionsOnASingleLine: Empty
                                  ^~~~~

YAML:15:19: error: unknown key 'BinPackArguments'
BinPackArguments: true
                  ^~~~
YAML:34:23: error: unknown key 'SpaceAfterCStyleCast'
SpaceAfterCStyleCast: true
                      ^~~~
YAML:3:30: error: unknown key 'AlignConsecutiveAssignments'
AlignConsecutiveAssignments: false
                             ^~~~~
YAML:8:36: error: unknown key 'AllowShortCaseLabelsOnASingleLine'
AllowShortCaseLabelsOnASingleLine: true
YAML:2:24: error: unknown key 'AlignAfterOpenBracket'
AlignAfterOpenBracket: true
                       ^~~~                        ^~~~
YAML:39:25: error: unknown key 'SpacesInSquareBrackets'
SpacesInSquareBrackets: false
                        ^~~~~
YAML:3:16: error: unknown key 'AlignOperands'
AlignOperands: false
               ^~~~~
Error reading /home/markus/Projekte/Elektra/current/.clang-format: Invalid argument
```

Which clang-format version is needed?

Can you disable that C/Doxygen-comments within `/**/` are reformatted?

Thanks, it looks nice!

**Comment by sanssecours** [comment]
> Yes, its 8 because of the default settings of most editors. I think the setting is ok, we can simply increase the maximum line length (ColumnLimit) to e.g. 150 to not have problems with some longer lines in high indentation depth.

For now I increased the value to 80 characters. This (or a very similar value) is also used in many other languages and style guides: 

- Python: 79
- RuboCop (Ruby): 80
- Java: 80 
- Linux Kernel: 80

> Additionally, we agreed to have spaces around *, which is not always the case in kdb.c

I changed `PointerAlignment` to `Middle`, which has the desired effect.

> There should be spaces before `(`.

This is also possible if we change `SpaceBeforeParens` to `Always`.

> We are still discussing if () (empty parenthesis) need a space before it, too. Would the clang-style support such an exception?

As far as I can tell: “No”. Currently there are only three options for `SpaceBeforeParens`: 

1. `Never`
2. `ControlStatements`
3.  `Always`

>  Is it ok to continue text after `clang-format off`?

Yes, code after the comment `// clang-format off` is not touched at all. There is no need to use `// clang-format on` at the end of a file, according to my test.

> Btw. my clang-format-3.5 has following errors with your yaml file (line numbers are wrong because I modified the file to get further errors):

I only set most of the shown options, so that we would have valid default values. I think the only interesting attributes here is `AlignAfterOpenBracket`. It looks like as if `clang-format` behaves as if the value is set to `true`, if I just delete it. My conclusion: Just remove all attributes shown in the error output.

>  Which clang-format version is needed?

I currently use version 3.7.1: `clang-format version 3.7.1 (tags/RELEASE_371/final)`

> Can you disable that C/Doxygen-comments within /**/ are reformatted?

Since I wasted some time with this: Here is a regular expression that matches a single Doxygen comment:

```re
/\*\*((?!\*/)[\S\s])*\*/
```

Clang-Format only checks **comments** for the value of `CommentPragmas` though. Therefore a regex that lets `clang-format` ignore Doxygen comments is much simpler : `^\*`

---

Here is the current version of `.clang_format`:

```yaml
AccessModifierOffset: -8
AlignEscapedNewlinesLeft: false
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: false
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: true
BinPackParameters: true
BreakBeforeBraces: Allman
BreakBeforeTernaryOperators: false
BreakConstructorInitializersBeforeComma: false
ColumnLimit: 80
CommentPragmas: ^\*
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 0
ContinuationIndentWidth: 8
Cpp11BracedListStyle: false
DerivePointerAlignment: false
DisableFormat: false
IndentCaseLabels: false
IndentWidth: 8
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: true
NamespaceIndentation: None
PointerAlignment: Middle
TabWidth: 8
MaxEmptyLinesToKeep: 2
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Always
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: false
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
UseTab: Always
```
